import type { Locale } from './translations';

const en = {
  carouselTitle: 'The story so far.', swipeChapters: 'Swipe to explore', scrollChapters: 'Scroll to explore',
  chapters: 'Chapters', cv: 'Career & curriculum vitae', title: 'A career in', titleAccent: 'five chapters.',
  intro: 'From economics to algorithms. From understanding risk to building something of my own. The experiences that shaped how I work.',
  scroll: 'Scroll through the story', record: 'The full record', recordNote: 'Education, experience and working languages. Dates as recorded in my CV.',
  scenes: ['The foundations', 'Learning the stakes', 'Models meet reality', 'Reading between lines', 'Building the practice'],
  sceneLabels: ['Economics × computer science', 'Risk × responsibility', 'Data × industry', 'Language × evidence', 'Italy × Turkey'],
  nextTitle: 'What comes next starts', nextAccent: 'with a conversation.', nextLink: 'Start a conversation', print: 'Print / save CV',
  contact: 'Contact', contactEyebrow: 'An idea starts with a connection', contactTitle: 'Let’s give your idea', contactAccent: 'a first page.',
  contactIntro: 'Four small questions. A thoughtful first message. Tell me what you have in mind, and we’ll take it from there.',
  guide: 'Your conversation guide', sceneAlt: 'An illuminated neuron suspended inside an open three-dimensional book.',
  sceneNote: 'Every answer makes another connection.', pause: 'Pause animation', play: 'Play animation',
  steps: ['Introduction', 'Direction', 'Your idea', 'Timing'],
  questions: ['First, what should I call you?', 'What brings you here?', 'What would a good outcome look like?', 'When would you like to begin?'],
  hints: ['A name is enough. Add your company if it helps.', 'Choose the closest fit. There is room to explain in the next step.', 'A problem, a possibility, or something you’d like to build. A few sentences will do.', 'An estimate is fine. This simply helps frame the conversation.'],
  name: 'Your name', namePlaceholder: 'How you’d like to be addressed', company: 'Company / organisation', optional: 'optional',
  idea: 'Your idea', ideaPlaceholder: 'We are working on… The part we would like help with is…',
  topics: ['Document intelligence & AI', 'Forecasting & financial analytics', 'Reporting & business intelligence', 'Italy–Turkey advisory', 'Something else'],
  timings: ['As soon as possible', 'In the next 1–3 months', 'Later this year', 'Just exploring'],
  next: 'Continue', back: 'Back', review: 'Review my message', step: 'Question', of: 'of',
  nameError: 'Please tell me your name.', ideaError: 'Please add at least 20 characters so I can understand your idea.',
  previewTitle: 'Your first page is ready.', previewHint: 'Make it sound like you, then choose where to continue.', messageLabel: 'Your message',
  whatsapp: 'Open WhatsApp', outlook: 'Open Outlook app', email: 'Open email app', outlookWeb: 'Outlook in browser',
  mailHint: 'On desktop, the email button opens your default mail app. Choose Outlook as your default to use it here.',
  sendNote: 'You review and send the message in the app. Nothing is sent automatically.', privacy: 'Your answers stay in this page until you choose a messaging app. No account needed.',
  edit: 'Edit answers', copy: 'Copy message', copied: 'Copied', copyFailed: 'Select and copy the message above.',
  direct: 'Prefer to start directly?', careerLink: 'Looking for my background? Explore Chapters',
  greeting: 'Hi Bumin,', introduction: 'My name is', from: 'from', interest: 'I’d like to discuss', timingLabel: 'Timing', closing: 'Would you be available to discuss the next steps?', subject: 'Project inquiry',
};
export type ExperienceCopy = typeof en;
const tr: ExperienceCopy = {
  carouselTitle: 'Buraya kadar gelen hikâye.', swipeChapters: 'Keşfetmek için kaydır', scrollChapters: 'Keşfetmek için kaydır',
  chapters: 'Bölümler', cv: 'Kariyer ve özgeçmiş', title: 'Beş bölümde', titleAccent: 'bir kariyer.',
  intro: 'Ekonomiden algoritmalara. Riski anlamaktan kendi işimi kurmaya. Çalışma biçimimi şekillendiren deneyimler.',
  scroll: 'Hikâyeyi kaydırarak keşfet', record: 'Özgeçmiş', recordNote: 'Eğitim, deneyim ve çalışma dilleri. Tarihler özgeçmişimdeki kayıtlara göredir.',
  scenes: ['Temeller', 'Sorumluluğu öğrenmek', 'Modeller gerçeklikle buluşuyor', 'Satır aralarını okumak', 'Kendi işimi kurmak'],
  sceneLabels: ['Ekonomi × bilgisayar bilimi', 'Risk × sorumluluk', 'Veri × endüstri', 'Dil × kanıt', 'İtalya × Türkiye'],
  nextTitle: 'Sıradaki bölüm', nextAccent: 'bir sohbetle başlar.', nextLink: 'Bir sohbet başlat', print: 'Yazdır / CV kaydet',
  contact: 'İletişim', contactEyebrow: 'Bir fikir bir bağlantıyla başlar', contactTitle: 'Fikrinize bir', contactAccent: 'ilk sayfa açalım.',
  contactIntro: 'Dört küçük soru. Özenli bir ilk mesaj. Aklınızdakini anlatın, birlikte devamını getirelim.',
  guide: 'Sohbet rehberiniz', sceneAlt: 'Açık, üç boyutlu bir kitabın içinde asılı duran ışıklı bir nöron.',
  sceneNote: 'Her yanıt yeni bir bağlantı kurar.', pause: 'Animasyonu duraklat', play: 'Animasyonu oynat',
  steps: ['Tanışma', 'Yön', 'Fikriniz', 'Zamanlama'],
  questions: ['Önce size nasıl hitap edeyim?', 'Sizi buraya getiren nedir?', 'İyi bir sonuç sizin için ne olurdu?', 'Ne zaman başlamak istersiniz?'],
  hints: ['İsminiz yeterli. İsterseniz şirketinizi de ekleyin.', 'En yakın seçeneği seçin. Sonraki adımda ayrıntıları anlatabilirsiniz.', 'Bir sorun, bir fırsat veya geliştirmek istediğiniz bir şey. Birkaç cümle yeterli.', 'Bir tahmin yeterli. Bu, sohbetin çerçevesini belirlemeye yardımcı olur.'],
  name: 'Adınız', namePlaceholder: 'Size nasıl hitap etmemi istersiniz?', company: 'Şirket / kuruluş', optional: 'isteğe bağlı',
  idea: 'Fikriniz', ideaPlaceholder: 'Üzerinde çalıştığımız konu… Yardım istediğimiz kısım…',
  topics: ['Belge zekâsı ve yapay zekâ', 'Tahminleme ve finansal analitik', 'Raporlama ve iş zekâsı', 'İtalya–Türkiye danışmanlığı', 'Başka bir konu'],
  timings: ['Mümkün olan en kısa sürede', 'Önümüzdeki 1–3 ay içinde', 'Bu yılın ilerleyen döneminde', 'Henüz araştırıyorum'],
  next: 'Devam', back: 'Geri', review: 'Mesajımı gözden geçir', step: 'Soru', of: '/',
  nameError: 'Lütfen adınızı yazın.', ideaError: 'Fikrinizi anlayabilmem için en az 20 karakter yazın.',
  previewTitle: 'İlk sayfanız hazır.', previewHint: 'Mesajı dilediğiniz gibi düzenleyin, ardından nerede devam edeceğinizi seçin.', messageLabel: 'Mesajınız',
  whatsapp: 'WhatsApp’ı aç', outlook: 'Outlook uygulamasını aç', email: 'E-posta uygulamasını aç', outlookWeb: 'Tarayıcıda Outlook',
  mailHint: 'Masaüstünde e-posta düğmesi varsayılan posta uygulamanızı açar. Outlook’u kullanmak için onu varsayılan olarak seçin.',
  sendNote: 'Mesajı uygulamada gözden geçirip siz gönderirsiniz. Hiçbir şey otomatik gönderilmez.', privacy: 'Bir mesajlaşma uygulaması seçene kadar yanıtlarınız bu sayfada kalır. Hesap gerekmez.',
  edit: 'Yanıtları düzenle', copy: 'Mesajı kopyala', copied: 'Kopyalandı', copyFailed: 'Yukarıdaki mesajı seçip kopyalayın.',
  direct: 'Doğrudan başlamak ister misiniz?', careerLink: 'Geçmişimi mi merak ediyorsunuz? Bölümleri keşfedin',
  greeting: 'Merhaba Bumin,', introduction: 'Ben', from: 'şirketinden', interest: 'Görüşmek istediğim konu', timingLabel: 'Zamanlama', closing: 'Sonraki adımları görüşmek için müsait olur musunuz?', subject: 'Proje hakkında görüşme',
};
const it: ExperienceCopy = {
  carouselTitle: 'La storia, fin qui.', swipeChapters: 'Scorri per esplorare', scrollChapters: 'Scorri per esplorare',
  chapters: 'Capitoli', cv: 'Carriera e curriculum vitae', title: 'Una carriera in', titleAccent: 'cinque capitoli.',
  intro: 'Dall’economia agli algoritmi. Dalla comprensione del rischio alla costruzione di una mia attività. Le esperienze che hanno formato il mio modo di lavorare.',
  scroll: 'Scorri la storia', record: 'Il curriculum completo', recordNote: 'Formazione, esperienze e lingue di lavoro. Date come riportate nel mio CV.',
  scenes: ['Le fondamenta', 'Imparare la responsabilità', 'I modelli incontrano la realtà', 'Leggere tra le righe', 'Costruire la pratica'],
  sceneLabels: ['Economia × informatica', 'Rischio × responsabilità', 'Dati × industria', 'Linguaggio × evidenza', 'Italia × Turchia'],
  nextTitle: 'Il prossimo capitolo inizia', nextAccent: 'con una conversazione.', nextLink: 'Inizia una conversazione', print: 'Stampa / salva CV',
  contact: 'Contatti', contactEyebrow: 'Un’idea inizia con una connessione', contactTitle: 'Diamo alla tua idea', contactAccent: 'una prima pagina.',
  contactIntro: 'Quattro piccole domande. Un primo messaggio curato. Raccontami cosa hai in mente, poi ne parliamo.',
  guide: 'La tua guida alla conversazione', sceneAlt: 'Un neurone luminoso sospeso all’interno di un libro tridimensionale aperto.',
  sceneNote: 'Ogni risposta crea una nuova connessione.', pause: 'Pausa animazione', play: 'Riprendi animazione',
  steps: ['Presentazione', 'Direzione', 'La tua idea', 'Tempistiche'],
  questions: ['Prima di tutto, come ti chiami?', 'Cosa ti porta qui?', 'Quale sarebbe un buon risultato?', 'Quando vorresti iniziare?'],
  hints: ['Basta il nome. Aggiungi l’azienda se è utile.', 'Scegli l’opzione più vicina. Nel prossimo passo potrai raccontare di più.', 'Un problema, una possibilità o qualcosa che vorresti costruire. Bastano poche frasi.', 'Va bene una stima. Serve solo a inquadrare la conversazione.'],
  name: 'Il tuo nome', namePlaceholder: 'Come vorresti essere chiamato?', company: 'Azienda / organizzazione', optional: 'facoltativo',
  idea: 'La tua idea', ideaPlaceholder: 'Stiamo lavorando a… La parte su cui vorremmo aiuto è…',
  topics: ['Document intelligence e AI', 'Previsioni e analisi finanziaria', 'Reporting e business intelligence', 'Consulenza Italia–Turchia', 'Qualcos’altro'],
  timings: ['Il prima possibile', 'Nei prossimi 1–3 mesi', 'Più avanti quest’anno', 'Sto solo esplorando'],
  next: 'Continua', back: 'Indietro', review: 'Rivedi il messaggio', step: 'Domanda', of: 'di',
  nameError: 'Inserisci il tuo nome.', ideaError: 'Aggiungi almeno 20 caratteri per aiutarmi a capire la tua idea.',
  previewTitle: 'La tua prima pagina è pronta.', previewHint: 'Rendila tua, poi scegli dove continuare.', messageLabel: 'Il tuo messaggio',
  whatsapp: 'Apri WhatsApp', outlook: 'Apri l’app Outlook', email: 'Apri l’app email', outlookWeb: 'Outlook nel browser',
  mailHint: 'Su desktop, il pulsante email apre l’app di posta predefinita. Imposta Outlook come predefinita per usarla qui.',
  sendNote: 'Rivedi e invii il messaggio nell’app. Nulla viene inviato automaticamente.', privacy: 'Le risposte restano in questa pagina finché non scegli un’app di messaggistica. Nessun account necessario.',
  edit: 'Modifica le risposte', copy: 'Copia messaggio', copied: 'Copiato', copyFailed: 'Seleziona e copia il messaggio qui sopra.',
  direct: 'Preferisci iniziare direttamente?', careerLink: 'Cerchi il mio percorso? Esplora i Capitoli',
  greeting: 'Ciao Bumin,', introduction: 'Mi chiamo', from: 'di', interest: 'Vorrei parlare di', timingLabel: 'Tempistiche', closing: 'Saresti disponibile per discutere i prossimi passi?', subject: 'Richiesta di progetto',
};
export const EXPERIENCE_COPY: Record<Locale, ExperienceCopy> = { en, tr, it };
export const getExperienceCopy = (locale: Locale) => EXPERIENCE_COPY[locale];
