/** Maintained accessibility, lifecycle, localization and scheduling adaptations. */
export function adaptShelf(input) {
  let code = input.replaceAll('\r\n', '\n');
  const patch = (from, to) => {
    if (!code.includes(from)) throw new Error(`Shelf adapter anchor missing: ${from.slice(0, 100)}`);
    code = code.replace(from, to);
  };
  const all = (from, to) => {
    if (!code.includes(from)) throw new Error(`Shelf adapter anchor missing: ${from}`);
    code = code.replaceAll(from, to);
  };
  code = `/** GENERATED by scripts/port-shelf-engine.mjs. Edit scripts/shelf-adapter.mjs.
 * Input: hash-checked repository port at 225f0ed; original vendor attribution below.
 * Current adaptations additionally provide scoped DOM/events, cancellation,
 * localized runtime copy, complete dialog focus order and bounded rendering.
 */\n` + code;
  patch(' * @returns {() => void} teardown', ` * @param {HTMLElement} options.root
 * @param {object} options.labels
 * @param {AbortSignal} options.signal
 * @param {(message: string) => void} options.onFallback
 * @returns {(() => void) & {pause: (paused: boolean) => void}} teardown`);
  patch('export function createShelf({ books, coverAtlasUrl, woodTextureUrl }) {', `export function createShelf({ root, books, labels: ui, signal, onFallback, coverAtlasUrl, woodTextureUrl }) {
  let disposed = false;
  const listeners = new AbortController();
  const cancelled = () => disposed || signal.aborted || !root.isConnected;
  const say = (key, values = {}) => ui[key].replace(/\\{(\\w+)\\}/g, (_, name) => String(values[name] ?? ''));
  const focusables = () => [...detailPanel.querySelectorAll('a[href], button, input, select, textarea, [tabindex]')]
    .filter(el => el.tabIndex >= 0 && !el.matches(':disabled') && !el.closest('[hidden], [inert], [aria-hidden="true"]')
      && el.getClientRects().length && getComputedStyle(el).visibility !== 'hidden');
  let inFrame = false;
  let initialized = false;
  let activeUntil = 0;
  let decorativePaused = false;
  const fontUI = getComputedStyle(root).getPropertyValue('--font-ui').trim() || 'Arial, sans-serif';
  const fontDisplay = getComputedStyle(root).getPropertyValue('--font-display').trim() || 'Georgia, serif';
`);
  all('document.querySelector(', 'root.querySelector(');
  patch('const rootStyle = document.documentElement.style;', 'const rootStyle = root.style;');
  patch(`    root.querySelector('meta[name="theme-color"]')?.setAttribute("content", palette.paper);`, '');
  // Localized labels cover both DOM announcements and decorative printed pages.
  const replacements = [
    ['`Select volume ${index + 1}: ${book.title}`', 'say("selectVolume", { index: index + 1, title: book.title })'],
    ['`Open ${book.title}`', '`${ui.open}: ${book.title}`'],
    ['`Selected volume ${selectedIndex + 1} of ${BOOKS.length}: ${book.title}. ${book.note}`', 'say("selectedVolume", { index: selectedIndex + 1, total: BOOKS.length, title: book.title, note: book.note })'],
    ['`Volume ${book.roman} · ${book.discipline}`', '`${ui.volume} ${book.roman} · ${book.discipline}`'],
    ['"Title page"', 'ui.titlePage'], ['`${book.chapters[0]} · Plate`', '`${book.chapters[0]} · ${ui.plate}`'],
    ['`${book.chapters[1]} · Notes`', '`${book.chapters[1]} · ${ui.notes}`'], ['`${book.chapters[2]} · System`', '`${book.chapters[2]} · ${ui.system}`'],
    ['"Colophon"', 'ui.colophon'], ['"Closed"', 'ui.closed'], ['"Click book to open"', 'ui.clickToOpen'],
    ['"Close book"', 'ui.closeBook'], ['"Open book"', 'ui.openBook'],
    ['"Drag pages · Drag cover to close · Background to orbit"', 'ui.readingHint'],
    ['"Drag cover or click once to open · Background to orbit"', 'ui.dragHint'],
    ['"Previous sample page"', 'ui.previousPage'], ['`Previous sample page: ${labels[currentSpread - 1]}`', '`${ui.previousPage}: ${labels[currentSpread - 1]}`'],
    ['"Next sample page"', 'ui.nextPage'], ['`Next sample page: ${labels[currentSpread + 1]}`', '`${ui.nextPage}: ${labels[currentSpread + 1]}`'],
    ['`Page ${currentSpread + 1} of ${SPREAD_COUNT}: ${labels[currentSpread]}.`', 'say("pageAnnouncement", { index: currentSpread + 1, total: SPREAD_COUNT, title: labels[currentSpread] })'],
    ['`${activeBook.data.title} opened to its title page. Drag a page horizontally or use the arrow controls to read.`', 'say("bookOpened", { title: activeBook.data.title })'],
    ['`${activeBook.data.title} closed. Drag the cover, click the book, or use Open book to begin reading.`', 'say("bookClosed", { title: activeBook.data.title })'],
    ['`Volume ${pad(index + 1)}`', '`${ui.volume} ${pad(index + 1)}`'],
    ['`Opening a closed copy of ${activeBook.data.title}. Drag the cover, click the book, or use Open book to begin reading.`', 'say("bookClosed", { title: activeBook.data.title })'],
    ['`Returning ${activeBook.data.title} to the shelf.`', 'say("returning", { title: activeBook.data.title })'],
    ['`${BOOKS[selectedIndex].title} returned to the shelf.`', 'say("returned", { title: BOOKS[selectedIndex].title })'],
    ['`Inspection view reset for ${BOOKS[selectedIndex].title}.`', 'say("viewReset", { title: BOOKS[selectedIndex].title })'],
    ['"The 3D view paused after losing its graphics context. The complete static catalog remains available; reload to restore inspection."', 'ui.contextLost'],
    ['"WebGL is unavailable in this browser. The complete static catalog remains available."', 'ui.unavailable'],
    ['"The interactive shelf could not be prepared. The complete static catalog remains available."', 'ui.failed'],
    ['WORKING VOLUMES  /  ${', '${ui.identity.toUpperCase()}  /  ${'],
    ['CHAPTER ${pad(chapterIndex + 1)}', '${ui.chapter.toUpperCase()} ${pad(chapterIndex + 1)}'],
    ['"CHAPTER 03"', '`${ui.chapter.toUpperCase()} 03`'],
    ['"PLATE 01  /  SYSTEM MOTIF"', '`${ui.plate.toUpperCase()} 01 / ${ui.system.toUpperCase()}`'],
    ['"PLATE 02  /  TECHNICAL SYSTEM"', '`${ui.plate.toUpperCase()} 02 / ${ui.system.toUpperCase()}`'],
    ['NOTES  /  ${', '${ui.notes.toUpperCase()}  /  ${'], ['"COLOPHON"', 'ui.colophon.toUpperCase()'],
    ['${book.binding}. ${book.format}. Conceived as an original editorial study for Working Volumes.', '${book.binding}. ${book.format}.'],
    ['`SPECIMEN ${book.roman} / ${book.seed}  ·  IMAGINED EDITION`', '`${book.roman} · ${ui.sampleEdition.toUpperCase()}`'],
    ['"AN IMAGINED EDITION"', 'ui.sampleEdition.toUpperCase()'],
    ['"Iowan Old Style", Baskerville, Georgia, serif', '"Instrument Serif", Georgia, serif'],
  ];
  for (const [from, to] of replacements) all(from, to);
  // Canvas does not resolve next/font's public names to its hashed families.
  code = code.replace(/ctx\.font = '([^'\n]+)';/g, (_, font) => 'ctx.font = `' + font + '`;');
  all('Inter, "Helvetica Neue", Arial, sans-serif', '${fontUI}');
  all('"Instrument Serif", Georgia, serif', '${fontDisplay}');
  patch('document.fonts.load("600 82px Inter")', 'document.fonts.load(`500 18px ${fontUI}`)');
  patch('if (mode !== "hero") return;\n    event.preventDefault();', 'if (mode !== "hero" || window.innerHeight < 600 || event.ctrlKey || event.metaKey || event.target !== canvas || !root.contains(document.activeElement)) return;\n    event.preventDefault();');
  patch('  function onKeyDown(event) {', `  function onKeyDown(event) {
    if (cancelled() || event.defaultPrevented || !root.contains(event.target)) return;
    if (event.target.closest('input, textarea, select, [contenteditable], .site-nav')) return;
    if (event.metaKey || event.ctrlKey || event.altKey) return;`);
  patch('      closeDetail();\n      return;', '      event.stopPropagation();\n      closeDetail();\n      return;');
  patch('      mode === "detail"\n      && !event.metaKey', '      mode === "detail"\n      && readingOpen\n      && detailPanel.contains(event.target)\n      && !event.metaKey');
  const start = code.indexOf('      const focusables = [');
  const end = code.indexOf('\n      return;', start);
  if (start < 0 || end < 0) throw new Error('Focus loop anchor missing');
  code = code.slice(0, start) + `      const items = focusables();
      const current = items.indexOf(document.activeElement);
      if (!items.length) return;
      if (current < 0 || (!event.shiftKey && current === items.length - 1) || (event.shiftKey && current === 0)) {
        event.preventDefault();
        items[event.shiftKey ? items.length - 1 : 0].focus();
      }` + code.slice(end);
  patch('    if (mode !== "hero" || event.metaKey || event.ctrlKey || event.altKey) return;', '    if (mode !== "hero" || !browseUi.contains(event.target) || event.metaKey || event.ctrlKey || event.altKey) return;');
  all('window.addEventListener("keydown", onKeyDown)', 'root.addEventListener("keydown", onKeyDown)');
  all('window.removeEventListener("keydown", onKeyDown)', 'root.removeEventListener("keydown", onKeyDown)');
  patch('requestAnimationFrame(() => focusReturnTarget?.focus?.({ preventScroll: true }));', 'if (!cancelled()) focusReturnTarget?.focus?.({ preventScroll: true });');
  // Original continuous decorative loop now has a bounded settling window.
  patch('    if (reducedMotion) return;\n    const dust', '    if (reducedMotion || decorativePaused) return;\n    const dust');
  patch('const idle = reducedMotion ? 0 :', 'const idle = reducedMotion || decorativePaused ? 0 :');
  patch('  function requestFrame() {\n    if (!rafId && !suspended) {', `  function requestFrame(renew = true) {
    if (cancelled() || !initialized) return;
    if (renew && !inFrame) activeUntil = performance.now() + 1800;
    if (!rafId && !suspended) {`);
  patch('    rafId = 0;\n    const delta', '    rafId = 0;\n    if (cancelled()) { disposeExperience(); return; }\n    if (suspended) return;\n    inFrame = true;\n    const delta');
  patch('const shouldContinue = !reducedMotion', 'const shouldContinue = (!reducedMotion && time < activeUntil)');
  patch('    if (shouldContinue && !suspended) requestFrame();', '    inFrame = false;\n    if (shouldContinue && !suspended) requestFrame(false);');
  patch('    suspended = document.hidden;', '    if (disposed) return;\n    suspended = document.hidden;');
  patch('  function showFallback(message) {', '  function showFallback(message) {\n    if (cancelled()) return;');
  patch('    fallbackStatus.textContent = message;', '    fallbackStatus.textContent = message;\n    disposeExperience();\n    onFallback(message);');
  patch('  function disposeExperience() {', `  function disposeExperience() {
    if (disposed) return;
    disposed = true;
    listeners.abort();
    signal.removeEventListener('abort', disposeExperience);`);
  patch('    renderer?.dispose();', '    renderer?.dispose();\n    renderer?.forceContextLoss();\n    renderer = undefined;');
  patch('    try {\n      await coverAtlasImage.decode();', '    if (cancelled()) return;\n    try {\n      await coverAtlasImage.decode();');
  patch('    try {\n      renderer = new THREE.WebGLRenderer({', '    if (cancelled()) return;\n    try {\n      renderer = new THREE.WebGLRenderer({');
  patch('    const pmremGenerator = new THREE.PMREMGenerator(renderer);\n    environmentTarget = pmremGenerator.fromScene(new RoomEnvironment(), 0.04);', `    const pmremGenerator = new THREE.PMREMGenerator(renderer);
    const roomEnvironment = new RoomEnvironment();
    try { environmentTarget = pmremGenerator.fromScene(roomEnvironment, 0.04); }
    finally { roomEnvironment.dispose(); pmremGenerator.dispose(); }`);
  patch('    pmremGenerator.dispose();', '');
  patch('    experience.classList.add("webgl-ready");', '    experience.classList.add("webgl-ready");\n    initialized = true;');
  patch('      if (!ready || suspended || !renderer) return;', '      if (!ready || cancelled() || !renderer) return;');
  // Anonymous button listeners must also be removed after partial initialization.
  code = code.replace(/(\w+\.addEventListener\("click", [^\n]+)\);/g, '$1, { signal: listeners.signal });');
  patch('  initialize().catch(() => {', `  signal.addEventListener('abort', disposeExperience, { once: true });
  if (signal.aborted) disposeExperience();
  disposeExperience.pause = (value) => { decorativePaused = value; requestFrame(); };
  if (!cancelled()) initialize().catch(() => {`);
  // The cover artwork remains intact on disk. Render it as neutral printed stock.
  code = code.replace('      ctx.drawImage(\n        coverAtlasImage,', '      ctx.filter = "grayscale(1)";\n      ctx.drawImage(\n        coverAtlasImage,');
  code = code.replace('      const edgeShade = ctx.createLinearGradient', '      ctx.filter = "none";\n      const edgeShade = ctx.createLinearGradient');
  code = code.replace('const texture = new THREE.Texture(woodTextureImage);', `const neutral = document.createElement('canvas');
    neutral.width = woodTextureImage.naturalWidth; neutral.height = woodTextureImage.naturalHeight;
    const paint = neutral.getContext('2d'); paint.filter = 'grayscale(1)'; paint.drawImage(woodTextureImage, 0, 0);
    const texture = new THREE.CanvasTexture(neutral);`);
  return code;
}
